version: '3.8'

services:
  web:
    build: .
    container_name: django_app
    ports:
      - "1234:1234"
    volumes:
      - ./media:/app/media  # Persist media files
      - ./static:/app/static  # Persist static files
    environment:
      - DEBUG=True
      - ALLOWED_HOSTS=*